apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rogfk-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-egrunnerverv-instance-gateway_rogfk_no
  fintlabs.no/org-id: rogfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "rogfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "rogfk.no"
      - op: add
        path: "/spec/url/basePath"
        value: "/beta"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/api/egrunnerverv/instances/971045698"
    target:
      kind: Application
      name: fint-flyt-egrunnerverv-instance-gateway

