apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aiven-kafka
spec:
  itemPath: "vaults/aks-alpha-vault/items/aiven-kafka"
---
apiVersion: "fintlabs.no/v1alpha1"
kind: NamOAuthClientApplicationResource
metadata:
  name: oauth2-client-flyt-egrunnerverv-instance-gateway
  labels:
    app.kubernetes.io/name: oauth2-client-flyt-egrunnerverv-instance-gateway
    app.kubernetes.io/instance: vlfk-no-oauth2-client-flyt-egrunnerverv-instance-gateway
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: oauth-client
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: vlfk.no
spec:
  grantTypes:
    - client_credentials
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: fint-flyt-egrunnerverv-instance-gateway
  name: fint-flyt-egrunnerverv-instance-gateway
spec:
  ports:
    - port: 8080
  type: ClusterIP
  selector:
    io.kompose.service: fint-flyt-egrunnerverv-instance-gateway
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fint-flyt-egrunnerverv-instance-gateway
  labels:
    app: fint-flyt-egrunnerverv-instance-gateway
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`flyt.vigoiks.no`) && PathPrefix(`/alpha/vlfk-no/api/egrunnerverv/instances`)
      kind: Rule
      services:
        - name: fint-flyt-egrunnerverv-instance-gateway
          port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-flyt-egrunnerverv-instance-gateway
  name: fint-flyt-egrunnerverv-instance-gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-flyt-egrunnerverv-instance-gateway
  template:
    metadata:
      labels:
        io.kompose.service: fint-flyt-egrunnerverv-instance-gateway
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: aiven-kafka-certificates
      containers:
        - image: fintlabsacr.azurecr.io/fint-flyt-egrunnerverv-instance-gateway:dummy
          name: fint-flyt-egrunnerverv-instance-gateway
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: aiven-kafka
          env:
            - { name: TZ, value: Europe/Oslo }
            - { name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx480M -verbose:gc' }
            - { name: fint.org-id, value: 'vlfk.no' }
            - { name: fint.flyt.base-url, value: 'https://vlfk-no-skjema.vigoiks.no' }
            - { name: fint.flyt.resource-server.security.api.external.enabled, value: 'true' }
            - { name: fint.flyt.resource-server.security.api.external.authorized-client-ids, value: '2' }
            - { name: spring.webflux.base-path, value: 'alpha/vlfk-no' }