apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mrfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-egrunnerverv-gateway_mrfylke_no
      fintlabs.no/org-id: mrfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "mrfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "mrfylke.no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/api/egrunnerverv/instances/944183779"
      - op: replace
        path: "/spec/env/3/value"
        value: "false"
      - op: replace
        path: "/spec/env/4/value"
        value: "false"
      - op: replace
        path: "/spec/env/6/value"
        value: "https://vigoiks.service-now.com/api/now/table"
      - op: replace
        path: "/spec/env/7/value"
        value: "https://vigoiks.service-now.com/oauth_token.do"
    target:
      kind: Application
      name: fint-flyt-egrunnerverv-gateway

