apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mrfylke-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-egrunnerverv-instance-gateway_mrfylke_no
  fintlabs.no/org-id: mrfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "mrfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "mrfylke.no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/api/egrunnerverv/instances/944183779"
    target:
      kind: Application
      name: fint-flyt-egrunnerverv-instance-gateway

