apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-egrunnerverv-gateway_nfk_no
      fintlabs.no/org-id: nfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "nfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "nfk.no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/api/egrunnerverv/instances/964982953"
      - op: replace
        path: "/spec/env/3/value"
        value: "false"
      - op: replace
        path: "/spec/env/4/value"
        value: "false"
    target:
      kind: Application
      name: fint-flyt-egrunnerverv-gateway

