apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-flyt-egrunnerverv-gateway
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-flyt-egrunnerverv-gateway
    app.kubernetes.io/instance: fint-flyt-egrunnerverv-gateway_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-flyt-egrunnerverv-gateway:sha-0000000
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'no-permission'
  database:
    database: fint-flyt
  url:
    hostname: flyt.vigoiks.no
    basePath: ""
  ingress:
    enabled: true
    basePath: path
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx700M'
    - name: fint.flyt.resource-server.security.api.external.enabled
      value: "true"
    - name: fint.flyt.resource-server.security.api.external.authorized-client-ids
      value: "2"
    - name: fint.flyt.egrunnerverv.checkSaksansvarligEpost
      value: "true"
    - name: fint.flyt.egrunnerverv.checkSaksbehandler
      value: "true"
    - name: fint.flyt.egrunnerverv.checkEmailDomain
      value: "true"
    - name: fint.flyt.egrunnerverv.base-url
      value: baseUrl
    - name: fint.flyt.egrunnerverv.token-uri
      value: tokenUrl
  envFrom:
    - secretRef:
        name: fint-flyt-egrunnerverv-dispatch-oauth2-client
    - secretRef:
        name: fint-flyt-file-oauth2-client
    - secretRef:
        name: fint-flyt-v1-slack-webhook
  resources:
    limits:
      memory: "750Mi"
      cpu: "500m"
    requests:
      memory: "512Mi"
      cpu: "100m"
  probes:
    readiness:
      path: /actuator/health
      port: 8080
      initialDelaySeconds: 0
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 3
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }