name: CI

on:
  push:
    branches: ['*']


jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: false
          #tags: ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}

      - name: Gradle build
        run: |
          ./gradlew build
          mkdir data
          cp ./build/libs/${GITHUB_REPOSITORY#*/}-*.jar ./data/app.jar

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{steps.get_repo.outputs.REPO}}
          path: ./data/app.jar